name: esm-python-analysis

channels:
  - esmvalgroup 
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - python=3.7
  - numpy >=1.14
  - xarray >=0.10.8
  - pandas >=0.22.0
  - cartopy >=0.16.0
  - matplotlib 
  - seaborn >=0.8.1
  - geopy >=1.17.0
  - basemap
  - netcdf4
  - cis
  - bokeh
  - metpy
  - jupyter
  - ipykernel
  - notebook >=5.6.0
  - scipy
  - scikit-learn
  - jupyterlab
  - nc-time-axis
  - PyTables
  - xlrd
  - memory_profiler
  - plotly
  - ipyleaflet
  - rasterio
  - tqdm
  - requests
  - pillow
  - branca
  - geopandas
  - voila
  - nodejs
  - pythreejs
  - bqplot
  - psyplot
  - psy-maps 
  - psyplot-gui 
  - psy-reg 
  - cdsapi 
  - folium
  - basemap-data-hires
  - plotly
  - rasterstats
  - cdo
  - nco
  - pyaerocom
  - julia
  - esmvalcore>=2.0.0b2,<2.1
  - graphviz
  - imagemagick
  - libunwind 
  - esmvaltool
  - pip:
      - dask_labextension
      - ipydatawidgets
      - sidecar
      - geojsoncontour
